import React from 'react';
import { StyleSheet, View } from 'react-native';
import Typography from '../../atomComponents/Typography';
import Flex from '../../atomComponents/Flex';
import { FONTS, SHADOWS } from '../../globalStyle/Theme';
import Sizer from '../../helpers/Sizer';
import { G } from './gardenUi';

export function SummaryRow({ label, value, accent, bold, primary }) {
  const valueColor = primary ? G.primary : accent ? G.sage : G.forest;
  return (
    <Flex jusContent="space-between" mB={6} extraStyle={{ width: '100%' }}>
      <Typography size={13} color={G.muted}>
        {label}
      </Typography>
      <Typography
        size={bold ? 15 : 13}
        color={valueColor}
        style={{ fontWeight: bold || accent ? '600' : '400', fontFamily: bold ? FONTS.display : FONTS.body }}>
        {value}
      </Typography>
    </Flex>
  );
}

export const commerceStyles = StyleSheet.create({
  qtyWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: G.cream,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 4,
    paddingHorizontal: 8,
  },
  qtyPlus: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: G.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stickyFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: Sizer.hSize(16),
    paddingTop: 14,
    backgroundColor: '#FFFFFF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: G.divider,
    shadowColor: '#1A3020',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 12,
  },
  cartRow: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 12,
    ...SHADOWS.soft,
  },
  promoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 14,
    marginTop: 4,
  },
  summary: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 16,
    marginTop: 4,
  },
  divider: { height: 1, backgroundColor: G.divider, marginVertical: 10 },
  step: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: G.divider,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepOn: { backgroundColor: G.primary },
  stepLine: { flex: 1, height: 1, backgroundColor: G.divider },
  addressCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 16,
    ...SHADOWS.soft,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: G.divider,
    backgroundColor: '#FFFFFF',
    marginBottom: 8,
  },
  optionRowOn: {
    backgroundColor: 'rgba(208,236,126,0.2)',
    borderColor: G.accent,
  },
  optionCopy: { flex: 1, minWidth: 0, paddingRight: 8 },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: G.divider,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterOn: { borderColor: G.primary, backgroundColor: G.primary },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: G.accent,
  },
  productHero: { position: 'relative' },
  productHeroNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Sizer.hSize(20),
    zIndex: 2,
  },
  glassBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1A3020',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  productCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: G.divider,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    shadowColor: '#1A3020',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 0,
  },
  sizeBtn: {
    flex: 1,
    minHeight: 52,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: G.divider,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
  },
  sizeBtnOn: {
    backgroundColor: G.primary,
    borderColor: G.primary,
    shadowColor: G.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 6,
    elevation: 3,
  },
  pdpCategoryPill: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: G.sageLight,
    marginBottom: 2,
  },
  pdpDescCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 16,
    marginTop: 6,
    ...SHADOWS.soft,
  },
  pdpTrustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 20,
    padding: 14,
    borderRadius: 16,
    backgroundColor: G.sageLight,
    borderWidth: 1,
    borderColor: 'rgba(74,124,68,0.12)',
  },
  careCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 12,
    alignItems: 'center',
    ...SHADOWS.soft,
  },
  orderRoot: {
    flexGrow: 1,
    backgroundColor: G.cream,
    alignItems: 'center',
    paddingHorizontal: Sizer.hSize(24),
    paddingBottom: 24,
  },
  checkCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: G.accent,
    alignItems: 'center',
    justifyContent: 'center',
    ...SHADOWS.card,
  },
  orderCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: G.divider,
    padding: 20,
    marginTop: 24,
    ...SHADOWS.card,
  },
  confirmedBadge: {
    backgroundColor: 'rgba(45,122,82,0.15)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  deliveryCard: {
    width: '100%',
    backgroundColor: G.primary,
    borderRadius: 24,
    padding: 20,
    marginTop: 16,
    overflow: 'hidden',
    ...SHADOWS.card,
  },
  orderActions: { width: '100%', marginTop: 'auto', gap: 10, paddingTop: 24 },
  primaryBtn: {
    height: 48,
    borderRadius: 16,
    backgroundColor: G.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineBtn: {
    height: 48,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: G.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
