import { StyleSheet } from 'react-native';
import { COLORS, SHADOWS, SPACING } from '../../globalStyle/Theme';
import Sizer from '../../helpers/Sizer';

export const learnStyles = StyleSheet.create({
  top: { paddingHorizontal: Sizer.hSize(SPACING.screenPx), paddingBottom: 10 },
  search: {
    flexDirection: 'row',
    alignItems: 'center',
    height: Sizer.hSize(44),
    marginTop: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    paddingHorizontal: 14,
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: Sizer.fS(14), color: COLORS.textPrimary },
  featured: {
    marginHorizontal: Sizer.hSize(SPACING.screenPx),
    borderRadius: 20,
    overflow: 'hidden',
    ...SHADOWS.card,
  },
  featuredOverlay: { position: 'absolute', left: 14, right: 14, bottom: 14 },
  featuredBadge: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.accent,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  catRow: { paddingHorizontal: Sizer.hSize(SPACING.screenPx), marginTop: 14, gap: 8 },
  catChip: {
    paddingHorizontal: 14,
    height: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  catChipOn: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  hPad: { paddingHorizontal: Sizer.hSize(SPACING.screenPx) },
  continueCard: {
    width: Sizer.hSize(240),
    marginRight: 10,
    flexDirection: 'row',
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 10,
    ...SHADOWS.soft,
  },
  progressTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.border,
    marginTop: 8,
    overflow: 'hidden',
  },
  progressFill: { height: '100%', backgroundColor: COLORS.primary },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 10,
    marginBottom: 10,
    ...SHADOWS.soft,
  },
  hero: { position: 'relative' },
  heroNav: {
    position: 'absolute',
    top: Sizer.vSize(48),
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Sizer.hSize(SPACING.screenPx),
  },
  glassBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroTitle: {
    position: 'absolute',
    bottom: 16,
    left: Sizer.hSize(SPACING.screenPx),
    right: Sizer.hSize(SPACING.screenPx),
  },
  progressCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    ...SHADOWS.soft,
  },
  continueBtn: {
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lessonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    marginBottom: 8,
  },
  lessonRowCurrent: { backgroundColor: 'rgba(208,236,126,0.25)', borderColor: COLORS.accent },
  lessonNum: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.cream,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineBtn: {
    marginTop: 16,
    height: 44,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
