import { StyleSheet } from 'react-native';
import { FONTS, SHADOWS, SPACING } from '../../../globalStyle/Theme';
import Sizer from '../../../helpers/Sizer';
import { G, gardenUi } from '../../_partials/gardenUi';

export const profileStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: G.cream,
  },
  /** Web: rounded-b-2xl bg-primary px-4 pb-6 pt-12 */
  profileHeader: {
    backgroundColor: G.primary,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: Sizer.hSize(16),
    paddingBottom: Sizer.vSize(24),
    alignItems: 'center',
    overflow: 'hidden',
  },
  headerBar: {
    position: 'absolute',
    left: Sizer.hSize(16),
    right: Sizer.hSize(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 2,
  },
  headerGlow: {
    position: 'absolute',
    right: -40,
    top: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(208,236,126,0.15)',
  },
  avatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: G.accent,
    borderWidth: 4,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  premiumBadge: {
    marginTop: 6,
    backgroundColor: G.accent,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
  },
  premiumLabel: {
    fontWeight: '600',
    color: G.primary,
    fontSize: Sizer.fS(10),
  },
  nameTitle: {
    fontFamily: FONTS.display,
    fontWeight: '700',
    fontSize: Sizer.fS(20),
    color: '#FFFFFF',
    marginTop: 12,
  },
  interestChip: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: Sizer.hSize(16),
    marginTop: 16,
  },
  statBox: {
    ...gardenUi.card,
    flex: 1,
    padding: 10,
    alignItems: 'center',
  },
  subCard: {
    marginHorizontal: Sizer.hSize(16),
    marginTop: 16,
    backgroundColor: G.primary,
    borderRadius: 12,
    padding: 16,
    overflow: 'hidden',
    ...SHADOWS.card,
  },
  activeBadge: {
    backgroundColor: G.accent,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  manageBtn: {
    flex: 1,
    height: 36,
    borderRadius: 8,
    backgroundColor: G.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  billingBtn: {
    flex: 1,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsGroup: {
    paddingHorizontal: Sizer.hSize(16),
    marginTop: 20,
  },
  settingsCard: {
    ...gardenUi.card,
    overflow: 'hidden',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  settingsBorder: { borderBottomWidth: 1, borderBottomColor: G.divider },
  signOut: {
    marginHorizontal: Sizer.hSize(16),
    marginTop: 20,
    marginBottom: 12,
    height: 40,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#C45C4A',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
