import { onboard01, onboard02, onboard03, onboard04, onboard05, onboard06, onboard07, onboard08, onboard09, onboard10, onboard11, communityPost1, communityPost2, projectThumb1, projectThumb2, projectThumb3 } from '../../assets/images';
import {
  BLOCK_VARIANT,
  CONTENT_ALIGN,
  FOOTER,
  IMAGE_POSITION,
  LIST_VARIANT,
  ONBOARDING_IMAGE,
  ONBOARDING_UI,
} from './onboardingUi';
import { withOnboardingPlaceholderImages } from './onboardingPlaceholderImages';

/** Shared illustration sizing — middle & bottom onboard slots */
const ONBOARD_ILLUSTRATION = {
  imageBox: { borderRadius: ONBOARDING_UI.radiusLg },
  imageFullBleed: false,
  imageResizeMode: 'contain',
  imageFlexFill: false,
  imageScale: 1,
  imageMarginTop: 16,
  bodyMarginTop: 8,
};

/** All onboarding slides — one layout, content + image box config only */
const ONBOARDING_SLIDE_DATA = [
  {
    id: 'welcome',
    imageKey: 'onboarding-welcome',
    imageSource: onboard01,
    imagePosition: IMAGE_POSITION.top,
    imageFullBleed: true,
    imageFlexFill: true,
    imageResizeMode: 'contain',
    imageBox: { borderRadius: 0 },
    contentAlign: CONTENT_ALIGN.left,
    footer: FOOTER.welcome,
    intro: 'Welcome to',
    showLogo: true,
    title: 'Your personal garden consultant.',
    titleSize: 20,
    bodyMarginTop: 8,
    body:
      "We'll help you design, build, and care for a garden that's perfect for you.",
  },
  {
    id: 'dream-garden',
    imageKey: 'onboarding-dream-garden',
    imageSource: null,
    imagePosition: IMAGE_POSITION.none,
    contentAlign: CONTENT_ALIGN.left,
    footer: FOOTER.standard,
    listVariant: LIST_VARIANT.iconList,
    title: "Let's build your dream garden.",
    lead: 'Trellis will help you:',
    bullets: [
      { label: 'Understand your space', icon: 'space' },
      { label: 'Recommend the right plants & products', icon: 'leaf' },
      { label: 'Create a personalized plan for you', icon: 'plan' },
      { label: 'Build your step-by-step task list', icon: 'tasks' },
      { label: 'Keep you on track & growing', icon: 'track' },
    ],
  },
  {
    id: 'smart-recommendations',
    imageKey: 'onboarding-smart-recommendations',
    imageSource: onboard02,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    contentAlign: CONTENT_ALIGN.center,
    footer: FOOTER.standard,
    listVariant: LIST_VARIANT.iconList,
    title: 'Smart recommendations just for you.',
    body:
      'We analyze your space, sunlight, climate, and goals to recommend the right plants, projects, and products that will thrive in your garden.',
    bullets: [
      { label: 'Right plants for your space', icon: 'house' },
      { label: 'Projects that fit your goals', icon: 'goals' },
      { label: 'Products within your budget', icon: 'bag' },
      { label: 'Tips tailored to your experience', icon: 'tips' },
    ],
  },
  {
    id: 'custom-plan',
    imageKey: 'onboarding-custom-plan',
    imageSource: onboard03,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    imageScale: 1.12,
    contentAlign: CONTENT_ALIGN.center,
    footer: FOOTER.standard,
    listVariant: LIST_VARIANT.checklist,
    title: 'A custom plan in minutes.',
    titleSize: 24,
    body:
      'From layout to shopping list to timeline—Trellis builds a personalized plan so you always know what to do next.',
    bodyMaxWidthRatio: 0.85,
    checklist: [
      'Garden layout',
      'Planting schedule',
      'Shopping list',
      'Step-by-step tasks',
    ],
  },
  {
    id: 'confidence',
    imageKey: 'onboarding-confidence',
    imageSource: onboard04,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    contentAlign: CONTENT_ALIGN.center,
    footer: FOOTER.standard,
    listVariant: LIST_VARIANT.iconList,
    title: 'Grow with confidence.',
    body:
      'We track your progress, celebrate wins, and adjust your plan as the seasons change—so your garden keeps thriving.',
    featureBox: {
      title: 'Monthly Garden Audit',
      items: [
        { label: 'Review your photos', icon: 'camera' },
        { label: 'Measure your progress', icon: 'ruler' },
        { label: 'Update recommendations', icon: 'refresh' },
        { label: 'Spot problems early', icon: 'alert' },
        { label: 'Plan ahead for next month', icon: 'calendar' },
      ],
    },
  },
  {
    id: 'monthly-audit',
    imageKey: 'onboarding-monthly-audit',
    imageSource: onboard05,
    imagePosition: IMAGE_POSITION.bottom,
    ...ONBOARD_ILLUSTRATION,
    contentAlign: CONTENT_ALIGN.left,
    footer: FOOTER.standard,
    listVariant: LIST_VARIANT.iconList,
    title: "We'll help your garden thrive all season long.",
    lead: 'Every month, Trellis will:',
    bullets: [
      { label: 'Review your garden photos', icon: 'camera' },
      { label: 'Measure your progress', icon: 'ruler' },
      { label: 'Update recommendations', icon: 'refresh' },
      { label: 'Spot problems early', icon: 'alert' },
      { label: 'Create next-month priorities', icon: 'calendar' },
    ],
  },
  {
    id: 'meet-sol',
    imageKey: 'onboarding-meet-sol',
    imageSource: onboard06,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    contentAlign: CONTENT_ALIGN.center,
    footer: FOOTER.standard,
    listVariant: LIST_VARIANT.iconList,
    title: 'Meet Sol',
    subtitle: 'Your personal garden consultant.',
    listHeading: 'Sol already knows:',
    bullets: [
      { label: 'Your space & balcony', icon: 'house' },
      { label: 'Your climate (NYC, Zone 7b)', icon: 'climate' },
      { label: 'Your goals & preferences', icon: 'star' },
      { label: 'Your plants & projects', icon: 'leaf' },
      { label: 'Your budget & timeline', icon: 'wallet' },
      { label: 'Your experience level', icon: 'person' },
    ],
  },
  {
    id: 'smart-tasks',
    imageKey: 'onboarding-smart-tasks',
    imageSource: onboard07,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    contentAlign: CONTENT_ALIGN.left,
    footer: FOOTER.standard,
    title: 'Stay on track with smart Tasks.',
    body:
      'Trellis turns your garden plan into easy daily and weekly tasks so you always know what to do and when.',
    blockVariant: BLOCK_VARIANT.taskCard,
    previewBlock: {
      title: "Today's Tasks",
      date: 'May 12',
      tasks: [
        { label: 'Water basil', checked: true },
        { label: 'Check tomato plants', checked: false },
        { label: 'Deadhead marigolds', checked: false },
      ],
      footerLink: 'View All Tasks',
    },
  },
  {
    id: 'community',
    imageKey: 'onboarding-community',
    imageSource: onboard08,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    contentAlign: CONTENT_ALIGN.left,
    footer: FOOTER.standard,
    title: "You're never gardening alone.",
    body:
      'Join a community of plant lovers to ask questions, share wins, and get inspired.',
    blockVariant: BLOCK_VARIANT.communityCard,
    previewBlock: {
      title: 'Community',
      actionLabel: 'See all',
      tabs: [
        { label: 'For You', active: true },
        { label: 'New Posts', active: false },
        { label: 'Local', active: false },
      ],
      post: {
        author: 'Sara from Brooklyn',
        time: '2h ago',
        text: 'My tomatoes are finally starting to flower! 🌿 🍅',
        likes: '24',
        comments: '8',
        images: [communityPost1, communityPost2],
      },
    },
  },
  {
    id: 'projects',
    imageKey: 'onboarding-projects',
    imageSource: onboard09,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    contentAlign: CONTENT_ALIGN.left,
    footer: FOOTER.standard,
    title: 'Build beautiful gardens, step by step.',
    body:
      'DIY projects and guides walk you through everything from raised beds to trellises and more.',
    blockVariant: BLOCK_VARIANT.projectsCard,
    previewBlock: {
      title: 'Projects',
      actionLabel: 'See all',
      items: [
        { title: 'Build a Raised Herb Garden', subtitle: 'Beginner · 1 weekend', imageSource: projectThumb1 },
        { title: 'DIY Trellis for Climbing Plants', subtitle: 'Easy · 2 hours', imageSource: projectThumb2 },
        { title: 'Create a Pollinator Flower Planter', subtitle: 'Beginner · 1 hour', imageSource: projectThumb3 },
      ],
    },
  },
  {
    id: 'diagnose',
    imageKey: 'onboarding-diagnose',
    imageSource: onboard10,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    imageScale: 1.2,
    contentAlign: CONTENT_ALIGN.center,
    footer: FOOTER.standard,
    title: 'Diagnose problems like a pro.',
    body:
      'Snap a photo and Sol will help you identify plant problems and give you clear solutions.',
    blockVariant: BLOCK_VARIANT.diagnoseCard,
    previewBlock: {
      eyebrow: 'Diagnose',
      issueLabel: 'Possible issue',
      issue: 'Aphids',
      description: 'Tiny insects sucking sap from your plant.',
      actionLabel: 'View Treatment Plan',
    },
  },
  {
    id: 'track-progress',
    imageKey: 'onboarding-track-progress',
    imageSource: onboard11,
    imagePosition: IMAGE_POSITION.middle,
    ...ONBOARD_ILLUSTRATION,
    imageScale: 1.15,
    contentAlign: CONTENT_ALIGN.center,
    footer: FOOTER.standard,
    nextLabel: 'Continue',
    title: 'Track your progress\nand celebrate wins.',
    body:
      'See how your garden grows over time\nwith progress tracking, harvest logs,\nand monthly recaps.',
    blockVariant: BLOCK_VARIANT.progressCard,
    previewBlock: {
      title: 'Your Progress',
      periodLabel: 'May ▾',
      stats: [
        { icon: 'flower', label: 'Plants Added', value: '12' },
        { icon: 'harvest', label: 'Harvested', value: '5 lbs' },
        { icon: 'tasks', label: 'Tasks Completed', value: '28' },
        {
          icon: 'sprout',
          label: 'Garden Score',
          value: '92',
          score: true,
          subtext: 'Great job!',
          progress: 92,
        },
      ],
    },
  },
];

/** Remote HTTP placeholders sized per imageBox — replace imageSource with local assets when ready */
export const ONBOARDING_SLIDES = withOnboardingPlaceholderImages(ONBOARDING_SLIDE_DATA);
